// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfUbKoDTNDMLR6-2GwunMHGBY_kKJJUgE',
    appId: '1:909994550689:web:218a4ae084a27d102597e0',
    messagingSenderId: '909994550689',
    projectId: 'car-store-daa53',
    authDomain: 'car-store-daa53.firebaseapp.com',
    storageBucket: 'car-store-daa53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKklwwhvNPekzgviuyG9_zAKXnwF2D0zI',
    appId: '1:909994550689:android:534a02771fe41c6d2597e0',
    messagingSenderId: '909994550689',
    projectId: 'car-store-daa53',
    storageBucket: 'car-store-daa53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnk25E4YI8E9LRRLBI25Q8kKGldipQmAM',
    appId: '1:909994550689:ios:d204272dd25ea27b2597e0',
    messagingSenderId: '909994550689',
    projectId: 'car-store-daa53',
    storageBucket: 'car-store-daa53.firebasestorage.app',
    iosBundleId: 'com.example.crossPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnk25E4YI8E9LRRLBI25Q8kKGldipQmAM',
    appId: '1:909994550689:ios:d204272dd25ea27b2597e0',
    messagingSenderId: '909994550689',
    projectId: 'car-store-daa53',
    storageBucket: 'car-store-daa53.firebasestorage.app',
    iosBundleId: 'com.example.crossPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfUbKoDTNDMLR6-2GwunMHGBY_kKJJUgE',
    appId: '1:909994550689:web:2b9a3942b05de1092597e0',
    messagingSenderId: '909994550689',
    projectId: 'car-store-daa53',
    authDomain: 'car-store-daa53.firebaseapp.com',
    storageBucket: 'car-store-daa53.firebasestorage.app',
  );
}
